ALTER TABLE users ADD COLUMN reminder_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN reminder_time TEXT NOT NULL DEFAULT '21:00';
ALTER TABLE users ADD COLUMN reminder_days TEXT NOT NULL DEFAULT '1,2,3,4,5';
